import { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { supabase } from '../../services/authService.js';
import SiteHeader from '../SiteHeader/SiteHeader.jsx';
import SiteFooter from '../SiteFooter/SiteFooter.jsx';
import styles from './ArticlePage.module.css';

function cleanContent(html) {
  if (!html) return '';
  // Strip everything up to and including the first </h1> — we render the title explicitly above
  let cleaned = html.replace(/^[\s\S]*?<\/h1>/i, '');
  // Strip leading <img> that follows — we render the hero image explicitly above
  cleaned = cleaned.replace(/^\s*<img[^>]*\/?>\s*/i, '');
  // Strip "Article generated by BabyLoveGrowth" attribution links/paragraphs
  cleaned = cleaned.replace(/<[^>]+>[^<]*Article generated by BabyLoveGrowth[^<]*<\/[^>]+>/gi, '');
  cleaned = cleaned.replace(/Article generated by BabyLoveGrowth/gi, '');
  return cleaned;
}

export default function ArticlePage() {
  const { slug } = useParams();
  const [article, setArticle] = useState(null);
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);

  useEffect(() => {
    setLoading(true);
    setNotFound(false);
    supabase
      .from('articles')
      .select('id, title, slug, excerpt, content_html, image_url, image_alt, published_at, json_ld, faq_json_ld')
      .eq('slug', slug)
      .single()
      .then(({ data, error }) => {
        if (error || !data) { setNotFound(true); }
        else { setArticle(data); }
        setLoading(false);
      });
  }, [slug]);

  return (
    <>
      <SiteHeader onSignInClick={() => {}} />

      <main className={styles.main}>
        {loading && (
          <div className={styles.loading}>
            <div className={styles.spinner} />
          </div>
        )}

        {!loading && notFound && (
          <div className={styles.notFound}>
            <h1>Article not found</h1>
            <p>This article may have been removed or the URL is incorrect.</p>
            <Link to="/" className={styles.backLink}>← Back to home</Link>
          </div>
        )}

        {!loading && article && (
          <>
            <Helmet>
              <title>{article.title} — Create My Listings</title>
              <meta name="description" content={article.excerpt ?? ''} />
              {article.json_ld && (
                <script type="application/ld+json">
                  {JSON.stringify(article.json_ld)}
                </script>
              )}
              {article.faq_json_ld && (
                <script type="application/ld+json">
                  {JSON.stringify(article.faq_json_ld)}
                </script>
              )}
            </Helmet>

            <article className={styles.article}>
              <div className={styles.articleInner}>

                {/* Back link */}
                <a href="/#articles" className={styles.backLink}>← Featured Articles</a>

                {/* Hero image */}
                {article.image_url && (
                  <div className={styles.heroWrap}>
                    <img
                      src={article.image_url}
                      alt={article.image_alt || article.title}
                      className={styles.heroImg}
                      referrerPolicy="no-referrer"
                    />
                  </div>
                )}

                {/* Title + date */}
                <h1 className={styles.title}>{article.title}</h1>
                {article.published_at && (
                  <p className={styles.date}>
                    {new Date(article.published_at).toLocaleDateString('en-US', {
                      month: 'long', day: 'numeric', year: 'numeric',
                    })}
                  </p>
                )}

                {/* Article body */}
                <div
                  className={styles.content}
                  dangerouslySetInnerHTML={{ __html: cleanContent(article.content_html) }}
                />
              </div>
            </article>
          </>
        )}
      </main>

      <SiteFooter />
    </>
  );
}
